services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: mydatabase
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s

  backend:
    build:
      context: ./web_app_backend
      dockerfile: ./Dockerfile
    environment:
      - APP_ENV=production
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=my-secret-pw
      - API_PORT=8081
      - DB_NAME=bdd_jump_higher
      - CORS_ALLOWED_ORIGIN=http://localhost:8080
    ports:
      - "8081:8081"
    depends_on:
      mysql:
        condition: service_healthy

  frontend:
    build:
      context: ./web_app_frontend
      dockerfile: ./Dockerfile

    ports:
      - "8080:80"  # Mapping container port 80 (Nginx) to host port 8080
    depends_on:
      - backend

volumes:
  mysql-data:
