services:
  frontend:
    build:
      context: ./web_app_frontend
      dockerfile: ./Dockerfile
    ports:
      - "8080:80"  # Mapping container port 80 (Nginx) to host port 8080
    depends_on:
      - backend

  backend:
    build:
      context: ./web_app_backend
      dockerfile: ./Dockerfile
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=my-secret-pw
      - DB_NAME=mydatabase
    ports:
      - "8081:8081"
    depends_on:
      - mysql
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/api/users"]
      interval: 10s
      retries: 10
      start_period: 10s
      timeout: 5s

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: mydatabase
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
