name: Golangci Backend Code Linter
run-name: ${{ github.actor }} Golangci Backend Code Linter

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.23.3

      - name: Download Dependencies
        run: go mod download
        working-directory: ./web_app_backend

      - name: Run golangci-lint
        run: golangci-lint run
        working-directory: ./web_app_backend